# Définition minimaliste pour exécuter l'image construite depuis la pipeline.
services:
  app:
    # Tag injecté par Azure Pipelines via la variable BUILD_BUILDID.
    image: myregistry.azurecr.io/mon-app:${BUILD_BUILDID:-latest}
    restart: unless-stopped
    ports:
      - "80:83"
    # Par défaut le conteneur tourne en production ; override via une variable d'environnement .env.
    environment:
      NODE_ENV: ${NODE_ENV:-production}