import { Monitor, Package } from 'lucide-react';
import type { ServiceArea } from './types';

export const SERVICE_AREAS: ServiceArea[] = [
  {
    slug: 'informatique',
    label: 'Informatique',
    quickAccess: { label: 'Informatique', icon: Monitor, href: '/services' },
    cards: [
      {
        title: 'Général',
        links: [
          { label: 'Documentations, notices, procédures', type: 'header' },
          { label: 'Informatique / charte informatique', type: 'text', separator: false },
          { label: 'Charte informatique', href: '#', type: 'link', separator: true },
        ],
      },
      {
        title: 'Matériel, réseaux et accès internet',
        links: [
          { label: 'Formulaire de demande', type: 'header' },
          { label: 'Informatique / charte informatique', type: 'text', separator: true },
          { label: 'Demande investissement', href: '#', type: 'link', separator: false },
          { label: 'Demande interventions', href: '#', type: 'link', separator: false },
        ],
      },
      {
        title: 'Site internet et intranet',
        links: [
          { label: 'Contact utile', type: 'header' },
          { label: 'Matthieu Nicolas', type: 'text', separator: false },
          { label: 'Documentations, notices, procédures', type: 'header', separator: true },
          { label: 'Informatique/internet', type: 'text', separator: false },
          { label: 'Site internet - mentions obligatoires', href: '#', type: 'link', separator: false },
          { label: 'Mailnblack - connexion compte Office 365', href: '#', type: 'link', separator: false },
          { label: 'Formulaire de demande', type: 'header', separator: true },
          { label: "Demande d'interventions informatique", href: '#', type: 'link', separator: false },
        ],
      },
      {
        title: 'Nautilus',
        links: [
          { label: 'Contact utiles', type: 'header' },
          { label: 'Catherine Jullin', type: 'text', separator: false },
          { label: 'Documentations, notices, procédures', type: 'header', separator: true },
          { label: 'Procédures internes / note de frais', type: 'text', separator: false },
          { label: 'Procédure de commandes voyages', href: '#', type: 'link', separator: false },
          { label: 'Horaires TGV 2025', href: '#', type: 'link', separator: false },
          { label: 'Manuel utilisateurs Notilus', href: '#', type: 'link', separator: false },
          { label: 'Place de déplacement multimodal', href: '#', type: 'link', separator: false },
          { label: 'Note de demande déplacement professionnel', href: '#', type: 'link', separator: false },
          { label: 'Notilus 2022 - Manuel utilisateurs', href: '#', type: 'link', separator: false },
          { label: 'Notilus 2022 - procédures simplifiée', href: '#', type: 'link', separator: false },
        ],
      },
      {
        title: 'Mobilités',
        links: [
          { label: 'Documentations, notices, procédures', type: 'header' },
          { label: 'Informatique / mobilités', type: 'text', separator: false },
          {
            label: 'Comment désactiver le mode push de son iPhone',
            href: '#',
            type: 'link',
            separator: true,
          },
          {
            label: 'Les sites internets glénat sur mobile',
            href: '#',
            type: 'link',
            separator: false,
          },
          {
            label: "Recevoir une alerte glénat'matin sur son iPhone",
            href: '#',
            type: 'link',
            separator: false,
          },
          { label: 'Formulaire de demande', type: 'header', separator: true },
          { label: "Demande d'interventions informatique", href: '#', type: 'link', separator: false },
        ],
      },
      {
        title: 'Bureautique',
        links: [
          { label: 'Documentations, notices, procédures', type: 'header' },
          { label: 'Informatique / Charte informatique', type: 'text', separator: false },
          {
            label: 'Se connecter aux calendriers partagés',
            href: '#',
            type: 'link',
            separator: true,
          },
          { label: "Documentation Glénat'Fée", href: '#', type: 'link', separator: false },
          {
            label: 'Réservation salle de reunion',
            href: '#',
            type: 'link',
            separator: false,
          },
          { label: 'Gestion absence via OWA', href: '#', type: 'link', separator: false },
          { label: 'Publipostage', href: '#', type: 'link', separator: false },
          {
            label: 'Outlook 2011 mac Calendrier  partagé',
            href: '#',
            type: 'link',
            separator: false,
          },
          {
            label: 'Office 365 OWA Calendrier partagé',
            href: '#',
            type: 'link',
            separator: false,
          },
          { label: 'Présentation de intranet', href: '#', type: 'link', separator: false },
          { label: 'Présentation du réseau Informatique', href: '#', type: 'link', separator: false },
          {
            label: 'Howto - Visio - Réservation d’une salle',
            href: '#',
            type: 'link',
            separator: false,
          },
          {
            label: 'Demande de disponibilité dans outlook',
            href: '#',
            type: 'link',
            separator: false,
          },
          { label: 'Procédures internes / note de frais', type: 'header', separator: true },
          { label: 'Manuel utilisateurs Notilus', href: '#', type: 'link', separator: false },
          {
            label: 'Plan de déplacements multimodal',
            href: '#',
            type: 'link',
            separator: false,
          },
          { label: 'Note demande de déplacement', href: '#', type: 'link', separator: false },
          { label: 'Conditions relatives aux frais', href: '#', type: 'link', separator: false },
        ],
      },
    ],
  },
  {
    slug: 'production',
    label: 'Production',
    quickAccess: { label: 'Production', icon: Package, href: '/services/production' },
    cards: [
      {
        title: 'Achats',
        links: [
          { label: 'Contacts utiles', type: 'header' },
          { label: 'Isabelle Follier', href: '#', type: 'link' },
          { label: 'Nicolas Rouher', href: '#', type: 'link' },
          { label: 'Formulaires de demande', type: 'header', separator: true },
          { label: 'Demande de devis de fabrication', href: '#', type: 'link' },
        ],
      },
      {
        title: 'Atelier',
        links: [
          { label: 'Contacts utiles', type: 'header' },
          { label: 'Damien Bonis', href: '#', type: 'link' },
          { label: 'Sabine Gisolo', href: '#', type: 'link' },
          { label: 'Documentations, notices, procédures', type: 'header', separator: true },
          { label: 'Production / lexique', type: 'text' },
          { label: 'Lexique technique prépresse, imprimerie v1', href: '#', type: 'link' },
          { label: 'Lexique Fabrication Français-Anglais v1', href: '#', type: 'link' },
          { label: 'Cahier des charges Lettrage - GLP', href: '#', type: 'link' },
          { label: 'Cahier des charges Word - Maquette Livre', href: '#', type: 'link' },
          { label: 'Gestion des profils ICC_interne Glénat', href: '#', type: 'link' },
          {
            label: 'Réglages des profils ICC_Auteurs-Dessinateurs-Coloristes',
            href: '#',
            type: 'link',
          },
          { label: 'Cahier des charges Exterieur PDF - GLP', href: '#', type: 'link' },
          { label: 'Cahier des charges extérieur NATIFS 2020', href: '#', type: 'link' },
          { label: 'Fin de prise en charge des polices Postscript', href: '#', type: 'link' },
          { label: 'Formulaires de demande', type: 'header', separator: true },
          { label: 'Demande de PDF', href: '#', type: 'link' },
          { label: "Demande d'image", href: '#', type: 'link' },
          { label: 'Demande de Natif (Xpress/Indesign)', href: '#', type: 'link' },
          { label: 'Demande de flipbook', href: '#', type: 'link' },
        ],
      },
      {
        title: 'Mac',
        links: [
          { label: 'Contacts utiles', type: 'header' },
          { label: 'Damien Bonis', href: '#', type: 'link' },
          { label: 'Documentations, notices, procédures', type: 'header', separator: true },
          { label: 'Production / Mac', type: 'text' },
          {
            label: 'Centre de gestion des logiciels-utilisateurs Mac',
            href: '#',
            type: 'link',
          },
          { label: 'Formulaires de demande', type: 'header', separator: true },
          { label: "Demande d'interventions informatique", href: '#', type: 'link' },
        ],
      },
      {
        title: 'Knowbox',
        links: [
          { label: 'Contacts utiles', type: 'header' },
          { label: 'Aurélie Demard', href: '#', type: 'link' },
          { label: 'Sabine Gisolo', href: '#', type: 'link' },
          { label: 'Documentations, notices, procédures', type: 'header', separator: true },
          { label: 'Production/knowbox', type: 'text' },
          { label: 'Word formate preview', href: '#', type: 'link' },
          {
            label: 'Procédures des fiches argus - preview livre',
            href: '#',
            type: 'link',
          },
        ],
      },
      {
        title: 'Maestro',
        links: [
          { label: 'Contacts utiles', type: 'header' },
          { label: 'Julien Baleria', href: '#', type: 'link' },
          { label: 'Aurélie Demard', href: '#', type: 'link' },
          {
            label: 'Documentations, notices, procédures',
            type: 'header',
            separator: true,
          },
          { label: 'Production / maestro', type: 'text' },
          {
            label: 'Notice Maestro - Utilisateur consultation',
            href: '#',
            type: 'link',
          },
          { label: 'Notice Maestro - Actions utilisateurs', href: '#', type: 'link' },
        ],
      },
    ],
  },
];
